"""Add user model

Revision ID: 21621973df21
Revises: 
Create Date: 2024-09-17 23:23:41.870445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21621973df21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('lu')
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('stp')
    # op.drop_table('stl')
    # op.drop_table('field')
    # op.drop_table('sta')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('sta',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('web_uk_id', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    # sa.Column('vid_iz', sa.VARCHAR(length=26), autoincrement=False, nullable=True),
    # sa.Column('tgf', sa.VARCHAR(length=31), autoincrement=False, nullable=True),
    # sa.Column('n_uk_tgf', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    # sa.Column('n_uk_rosg', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    # sa.Column('name_otch', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('name_otch1', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('avts', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('god_nach', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    # sa.Column('god_end', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    # sa.Column('org_isp', sa.VARCHAR(length=193), autoincrement=False, nullable=True),
    # sa.Column('in_n_tgf', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    # sa.Column('in_n_rosg', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('nom_1000', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    # sa.Column('method', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    # sa.Column('scale', sa.VARCHAR(length=26), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='sta_pkey')
    # )
    # op.create_table('field',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('year', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('tip', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('areaoil', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('nom', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('oil', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('gas', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('condensat', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('name_ru', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('oblast', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('stadia', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('note', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('istochnik', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('ftype', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='field_pkey')
    # )
    # op.create_table('stl',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('web_uk_id', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    # sa.Column('vid_iz', sa.VARCHAR(length=26), autoincrement=False, nullable=True),
    # sa.Column('tgf', sa.VARCHAR(length=31), autoincrement=False, nullable=True),
    # sa.Column('n_uk_tgf', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    # sa.Column('n_uk_rosg', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    # sa.Column('name_otch', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('name_otch1', sa.VARCHAR(length=108), autoincrement=False, nullable=True),
    # sa.Column('avts', sa.VARCHAR(length=179), autoincrement=False, nullable=True),
    # sa.Column('god_nach', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    # sa.Column('god_end', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    # sa.Column('org_isp', sa.VARCHAR(length=192), autoincrement=False, nullable=True),
    # sa.Column('in_n_tgf', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    # sa.Column('in_n_rosg', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    # sa.Column('nom_1000', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    # sa.Column('method', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    # sa.Column('scale', sa.VARCHAR(length=26), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='stl_pkey')
    # )
    # op.create_table('stp',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('web_uk_id', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    # sa.Column('vid_iz', sa.VARCHAR(length=26), autoincrement=False, nullable=True),
    # sa.Column('tgf', sa.VARCHAR(length=31), autoincrement=False, nullable=True),
    # sa.Column('n_uk_tgf', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    # sa.Column('n_uk_rosg', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    # sa.Column('name_otch', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('name_otch1', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.Column('avts', sa.VARCHAR(length=161), autoincrement=False, nullable=True),
    # sa.Column('god_nach', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    # sa.Column('god_end', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    # sa.Column('org_isp', sa.VARCHAR(length=190), autoincrement=False, nullable=True),
    # sa.Column('in_n_tgf', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    # sa.Column('in_n_rosg', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    # sa.Column('nom_1000', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    # sa.Column('method', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    # sa.Column('scale', sa.VARCHAR(length=26), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='stp_pkey')
    # )
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # op.create_table('lu',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('areaoil', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('area_lic', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('year', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('nom_zsngp', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('nom_list', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    # sa.Column('nom', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('data_start', sa.DATE(), autoincrement=False, nullable=True),
    # sa.Column('data_end', sa.DATE(), autoincrement=False, nullable=True),
    # sa.Column('vid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('ftype', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    # sa.Column('name_rus', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    # sa.Column('anumber', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('sostiyanie', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('priznak', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('nom_lic', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('head_nedro', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    # sa.Column('oblast', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    # sa.Column('zngp', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('nedropolz', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    # sa.Column('nedropol', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    # sa.Column('nom_urfo', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('authority', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='lu_pkey')
    # )
    # ### end Alembic commands ###
